### ISSUE TITLE
The example app doesnt redirect back to application from safari browser

### ISSUE THREAD

**Issue by agenthunt** [magus/react-native-facebook-login#15] opened 2015-06-26 02:54 UTC
The example app doesnt redirect back to application from safari browser. Any thoughts ?

**Comment by magus** [comment] 2015-06-26 04:00
Can you share your package.json with me? :)

**Comment by magus** [comment] 2015-06-26 04:05
Hm I can't seem to repro, can you share your package.json? Did you make any changes? What version of react-native?

**Comment by agenthunt** [comment] 2015-06-26 04:20
Sorry, I had the app id twice in the URL schemes.  Thanks.

**Comment by magus** [comment] 2015-06-26 04:21
I just updated to react-native 0.6.0 and everything seems to be working as intended still! Feel free to update the latest version it'll be on npm in a few moments.

Going to close this out, thanks for using it! Cheers :+1:

**Closed by magus** 2015-06-26 04:21 UTC
